services:
  - type: web
    name: facial-attendance-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: localhost
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: 2004
      - key: DB_NAME
        value: bcaibm_attendance
      - key: SECRET_KEY
        value: e3f4a9cbd8224c90bfb4a7e2a1dfebc8
